name: stack_three_d1

task_name: stack_three_d1
lazy_eval: false

shape_meta: &shape_meta
  obs:
    agentview_image:
      shape: [84, 84, 3]       # HWC, native MimicGen resolution
      type: rgb
    robot0_eye_in_hand_image:
      shape: [84, 84, 3]
      type: rgb
    robot0_eef_pos:
      shape: [3]
      type: state
    robot0_eef_quat:
      shape: [4]
      type: state
    robot0_gripper_qpos:
      shape: [2]
      type: state
  action:
    shape: [7]


env_runner:
  _target_: oat.env_runner.robomimic_runner.RobomimicRunner
  dataset_path: data/robomimic/datasets/stack_three_d1/stack_three_d1.hdf5
  shape_meta: *shape_meta
  n_train: 6
  n_train_vis: 2
  train_start_idx: 0
  n_test: 50
  n_test_vis: 4
  test_start_seed: 100000
  n_obs_steps: ${n_obs_steps}
  n_action_steps: ${n_action_steps}
  max_episode_steps: 400
  fps: 10
  crf: 22
  n_parallel_envs: 4


dataset:
  _target_: oat.dataset.zarr_dataset.ZarrDataset
  zarr_path: data/mimicgen/stack_three_d1_N${training.num_demo}.zarr
  obs_keys:
    - agentview_image
    - robot0_eye_in_hand_image
    - robot0_eef_pos
    - robot0_eef_quat
    - robot0_gripper_qpos
  action_key: action
  n_obs_steps: ${n_obs_steps}
  n_action_steps: ${horizon}
  seed: ${seed}
  val_ratio: 0.1
